packages:
  - 'packages/*'
  - 'packages/clients/*'
  - 'packages/integrations/*'
  - 'packages/shared/*'
  - 'tools/*'
  - 'examples/*'

catalog:
  # Shared dependencies across the monorepo
  typescript: ^5.3.3
  "@types/node": ^20.10.5
  vitest: ^1.1.0
  "@vitest/ui": ^1.1.0
  zod: ^3.22.4
  
  # Build tools
  tsup: ^8.0.1
  rollup: ^4.9.1
  
  # Linting and formatting
  eslint: ^8.56.0
  prettier: ^3.2.5
  
  # Testing
  "@testing-library/jest-dom": ^6.1.5
  
  # Vector database clients
  "@pgvector/pg": ^0.1.2
  chromadb: ^1.7.3
  qdrant-js: ^1.7.0
  
  # MCP related
  "@anthropic/mcp": ^0.1.0
  
  # HTTP and API
  fastify: ^4.25.2
  "@fastify/cors": ^8.4.2
  "@fastify/swagger": ^8.13.0
  
  # CLI tools
  commander: ^11.1.0
  inquirer: ^9.2.12
  chalk: ^5.3.0
  
  # Database and storage
  pg: ^8.11.3
  redis: ^4.6.12
  neo4j-driver: ^5.15.0